from . import Day01
from . import Day02
from . import Day03
from . import Day04
from . import Day05
from . import Day06
from . import Day07
from . import Day08
from . import Day09
from . import Day10
from . import Day11
from . import Day12
from . import Day13
from . import Day14
from . import Day15
